/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as EmployerIndexRouteImport } from './routes/employer.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as EmployerVerificationRouteImport } from './routes/employer.verification'
import { Route as EmployerSettingsRouteImport } from './routes/employer.settings'
import { Route as EmployerNotificationsRouteImport } from './routes/employer.notifications'
import { Route as EmployerCvSearchRouteImport } from './routes/employer.cv-search'
import { Route as EmployerBillingRouteImport } from './routes/employer.billing'
import { Route as EmployerAtsRouteImport } from './routes/employer.ats'
import { Route as EmployerAssessmentsRouteImport } from './routes/employer.assessments'
import { Route as EmployerApplicantsRouteImport } from './routes/employer.applicants'
import { Route as PublicPricingRouteImport } from './routes/_public.pricing'
import { Route as PublicForEmployersRouteImport } from './routes/_public.for-employers'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as EmployerJobsIndexRouteImport } from './routes/employer.jobs.index'
import { Route as PublicJobsIndexRouteImport } from './routes/_public.jobs.index'
import { Route as EmployerJobsNewRouteImport } from './routes/employer.jobs.new'
import { Route as EmployerApplicantsIdRouteImport } from './routes/employer.applicants.$id'
import { Route as PublicJobsIdRouteImport } from './routes/_public.jobs.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerIndexRoute = EmployerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployerRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const EmployerVerificationRoute = EmployerVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerSettingsRoute = EmployerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerNotificationsRoute = EmployerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerCvSearchRoute = EmployerCvSearchRouteImport.update({
  id: '/cv-search',
  path: '/cv-search',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerBillingRoute = EmployerBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerAtsRoute = EmployerAtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerAssessmentsRoute = EmployerAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerApplicantsRoute = EmployerApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => EmployerRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForEmployersRoute = PublicForEmployersRouteImport.update({
  id: '/for-employers',
  path: '/for-employers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const EmployerJobsIndexRoute = EmployerJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => EmployerRoute,
} as any)
const PublicJobsIndexRoute = PublicJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => PublicRoute,
} as any)
const EmployerJobsNewRoute = EmployerJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerApplicantsIdRoute = EmployerApplicantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployerApplicantsRoute,
} as any)
const PublicJobsIdRoute = PublicJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/employer': typeof EmployerRouteWithChildren
  '/login': typeof LoginRoute
  '/about': typeof PublicAboutRoute
  '/for-employers': typeof PublicForEmployersRoute
  '/pricing': typeof PublicPricingRoute
  '/employer/applicants': typeof EmployerApplicantsRouteWithChildren
  '/employer/assessments': typeof EmployerAssessmentsRoute
  '/employer/ats': typeof EmployerAtsRoute
  '/employer/billing': typeof EmployerBillingRoute
  '/employer/cv-search': typeof EmployerCvSearchRoute
  '/employer/notifications': typeof EmployerNotificationsRoute
  '/employer/settings': typeof EmployerSettingsRoute
  '/employer/verification': typeof EmployerVerificationRoute
  '/employer/': typeof EmployerIndexRoute
  '/jobs/$id': typeof PublicJobsIdRoute
  '/employer/applicants/$id': typeof EmployerApplicantsIdRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/jobs/': typeof PublicJobsIndexRoute
  '/employer/jobs/': typeof EmployerJobsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof PublicAboutRoute
  '/for-employers': typeof PublicForEmployersRoute
  '/pricing': typeof PublicPricingRoute
  '/employer/applicants': typeof EmployerApplicantsRouteWithChildren
  '/employer/assessments': typeof EmployerAssessmentsRoute
  '/employer/ats': typeof EmployerAtsRoute
  '/employer/billing': typeof EmployerBillingRoute
  '/employer/cv-search': typeof EmployerCvSearchRoute
  '/employer/notifications': typeof EmployerNotificationsRoute
  '/employer/settings': typeof EmployerSettingsRoute
  '/employer/verification': typeof EmployerVerificationRoute
  '/': typeof PublicIndexRoute
  '/employer': typeof EmployerIndexRoute
  '/jobs/$id': typeof PublicJobsIdRoute
  '/employer/applicants/$id': typeof EmployerApplicantsIdRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/jobs': typeof PublicJobsIndexRoute
  '/employer/jobs': typeof EmployerJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/employer': typeof EmployerRouteWithChildren
  '/login': typeof LoginRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/for-employers': typeof PublicForEmployersRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/employer/applicants': typeof EmployerApplicantsRouteWithChildren
  '/employer/assessments': typeof EmployerAssessmentsRoute
  '/employer/ats': typeof EmployerAtsRoute
  '/employer/billing': typeof EmployerBillingRoute
  '/employer/cv-search': typeof EmployerCvSearchRoute
  '/employer/notifications': typeof EmployerNotificationsRoute
  '/employer/settings': typeof EmployerSettingsRoute
  '/employer/verification': typeof EmployerVerificationRoute
  '/_public/': typeof PublicIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/_public/jobs/$id': typeof PublicJobsIdRoute
  '/employer/applicants/$id': typeof EmployerApplicantsIdRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/_public/jobs/': typeof PublicJobsIndexRoute
  '/employer/jobs/': typeof EmployerJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employer'
    | '/login'
    | '/about'
    | '/for-employers'
    | '/pricing'
    | '/employer/applicants'
    | '/employer/assessments'
    | '/employer/ats'
    | '/employer/billing'
    | '/employer/cv-search'
    | '/employer/notifications'
    | '/employer/settings'
    | '/employer/verification'
    | '/employer/'
    | '/jobs/$id'
    | '/employer/applicants/$id'
    | '/employer/jobs/new'
    | '/jobs/'
    | '/employer/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/for-employers'
    | '/pricing'
    | '/employer/applicants'
    | '/employer/assessments'
    | '/employer/ats'
    | '/employer/billing'
    | '/employer/cv-search'
    | '/employer/notifications'
    | '/employer/settings'
    | '/employer/verification'
    | '/'
    | '/employer'
    | '/jobs/$id'
    | '/employer/applicants/$id'
    | '/employer/jobs/new'
    | '/jobs'
    | '/employer/jobs'
  id:
    | '__root__'
    | '/_public'
    | '/employer'
    | '/login'
    | '/_public/about'
    | '/_public/for-employers'
    | '/_public/pricing'
    | '/employer/applicants'
    | '/employer/assessments'
    | '/employer/ats'
    | '/employer/billing'
    | '/employer/cv-search'
    | '/employer/notifications'
    | '/employer/settings'
    | '/employer/verification'
    | '/_public/'
    | '/employer/'
    | '/_public/jobs/$id'
    | '/employer/applicants/$id'
    | '/employer/jobs/new'
    | '/_public/jobs/'
    | '/employer/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  EmployerRoute: typeof EmployerRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/': {
      id: '/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof EmployerIndexRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/employer/verification': {
      id: '/employer/verification'
      path: '/verification'
      fullPath: '/employer/verification'
      preLoaderRoute: typeof EmployerVerificationRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/settings': {
      id: '/employer/settings'
      path: '/settings'
      fullPath: '/employer/settings'
      preLoaderRoute: typeof EmployerSettingsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/notifications': {
      id: '/employer/notifications'
      path: '/notifications'
      fullPath: '/employer/notifications'
      preLoaderRoute: typeof EmployerNotificationsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/cv-search': {
      id: '/employer/cv-search'
      path: '/cv-search'
      fullPath: '/employer/cv-search'
      preLoaderRoute: typeof EmployerCvSearchRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/billing': {
      id: '/employer/billing'
      path: '/billing'
      fullPath: '/employer/billing'
      preLoaderRoute: typeof EmployerBillingRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/ats': {
      id: '/employer/ats'
      path: '/ats'
      fullPath: '/employer/ats'
      preLoaderRoute: typeof EmployerAtsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/assessments': {
      id: '/employer/assessments'
      path: '/assessments'
      fullPath: '/employer/assessments'
      preLoaderRoute: typeof EmployerAssessmentsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/applicants': {
      id: '/employer/applicants'
      path: '/applicants'
      fullPath: '/employer/applicants'
      preLoaderRoute: typeof EmployerApplicantsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/for-employers': {
      id: '/_public/for-employers'
      path: '/for-employers'
      fullPath: '/for-employers'
      preLoaderRoute: typeof PublicForEmployersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/employer/jobs/': {
      id: '/employer/jobs/'
      path: '/jobs'
      fullPath: '/employer/jobs/'
      preLoaderRoute: typeof EmployerJobsIndexRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/_public/jobs/': {
      id: '/_public/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof PublicJobsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/employer/jobs/new': {
      id: '/employer/jobs/new'
      path: '/jobs/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof EmployerJobsNewRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/applicants/$id': {
      id: '/employer/applicants/$id'
      path: '/$id'
      fullPath: '/employer/applicants/$id'
      preLoaderRoute: typeof EmployerApplicantsIdRouteImport
      parentRoute: typeof EmployerApplicantsRoute
    }
    '/_public/jobs/$id': {
      id: '/_public/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof PublicJobsIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicForEmployersRoute: typeof PublicForEmployersRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicJobsIdRoute: typeof PublicJobsIdRoute
  PublicJobsIndexRoute: typeof PublicJobsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicForEmployersRoute: PublicForEmployersRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicJobsIdRoute: PublicJobsIdRoute,
  PublicJobsIndexRoute: PublicJobsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface EmployerApplicantsRouteChildren {
  EmployerApplicantsIdRoute: typeof EmployerApplicantsIdRoute
}

const EmployerApplicantsRouteChildren: EmployerApplicantsRouteChildren = {
  EmployerApplicantsIdRoute: EmployerApplicantsIdRoute,
}

const EmployerApplicantsRouteWithChildren =
  EmployerApplicantsRoute._addFileChildren(EmployerApplicantsRouteChildren)

interface EmployerRouteChildren {
  EmployerApplicantsRoute: typeof EmployerApplicantsRouteWithChildren
  EmployerAssessmentsRoute: typeof EmployerAssessmentsRoute
  EmployerAtsRoute: typeof EmployerAtsRoute
  EmployerBillingRoute: typeof EmployerBillingRoute
  EmployerCvSearchRoute: typeof EmployerCvSearchRoute
  EmployerNotificationsRoute: typeof EmployerNotificationsRoute
  EmployerSettingsRoute: typeof EmployerSettingsRoute
  EmployerVerificationRoute: typeof EmployerVerificationRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
  EmployerJobsNewRoute: typeof EmployerJobsNewRoute
  EmployerJobsIndexRoute: typeof EmployerJobsIndexRoute
}

const EmployerRouteChildren: EmployerRouteChildren = {
  EmployerApplicantsRoute: EmployerApplicantsRouteWithChildren,
  EmployerAssessmentsRoute: EmployerAssessmentsRoute,
  EmployerAtsRoute: EmployerAtsRoute,
  EmployerBillingRoute: EmployerBillingRoute,
  EmployerCvSearchRoute: EmployerCvSearchRoute,
  EmployerNotificationsRoute: EmployerNotificationsRoute,
  EmployerSettingsRoute: EmployerSettingsRoute,
  EmployerVerificationRoute: EmployerVerificationRoute,
  EmployerIndexRoute: EmployerIndexRoute,
  EmployerJobsNewRoute: EmployerJobsNewRoute,
  EmployerJobsIndexRoute: EmployerJobsIndexRoute,
}

const EmployerRouteWithChildren = EmployerRoute._addFileChildren(
  EmployerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  EmployerRoute: EmployerRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
