/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/_account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as AccountWishlistsRouteImport } from './routes/_account.wishlists'
import { Route as AccountSettingsRouteImport } from './routes/_account.settings'
import { Route as AccountProfileRouteImport } from './routes/_account.profile'
import { Route as AccountNotificationsRouteImport } from './routes/_account.notifications'
import { Route as AccountJobSuggestionsRouteImport } from './routes/_account.job-suggestions'
import { Route as AccountCvRouteImport } from './routes/_account.cv'
import { Route as AccountAssessmentsRouteImport } from './routes/_account.assessments'
import { Route as AccountApplicationsRouteImport } from './routes/_account.applications'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/_account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWishlistsRoute = AccountWishlistsRouteImport.update({
  id: '/wishlists',
  path: '/wishlists',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountJobSuggestionsRoute = AccountJobSuggestionsRouteImport.update({
  id: '/job-suggestions',
  path: '/job-suggestions',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCvRoute = AccountCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAssessmentsRoute = AccountAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AccountRoute,
} as any)
const AccountApplicationsRoute = AccountApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/applications': typeof AccountApplicationsRoute
  '/assessments': typeof AccountAssessmentsRoute
  '/cv': typeof AccountCvRoute
  '/job-suggestions': typeof AccountJobSuggestionsRoute
  '/notifications': typeof AccountNotificationsRoute
  '/profile': typeof AccountProfileRoute
  '/settings': typeof AccountSettingsRoute
  '/wishlists': typeof AccountWishlistsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/applications': typeof AccountApplicationsRoute
  '/assessments': typeof AccountAssessmentsRoute
  '/cv': typeof AccountCvRoute
  '/job-suggestions': typeof AccountJobSuggestionsRoute
  '/notifications': typeof AccountNotificationsRoute
  '/profile': typeof AccountProfileRoute
  '/settings': typeof AccountSettingsRoute
  '/wishlists': typeof AccountWishlistsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_account': typeof AccountRouteWithChildren
  '/about': typeof AboutRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_account/applications': typeof AccountApplicationsRoute
  '/_account/assessments': typeof AccountAssessmentsRoute
  '/_account/cv': typeof AccountCvRoute
  '/_account/job-suggestions': typeof AccountJobSuggestionsRoute
  '/_account/notifications': typeof AccountNotificationsRoute
  '/_account/profile': typeof AccountProfileRoute
  '/_account/settings': typeof AccountSettingsRoute
  '/_account/wishlists': typeof AccountWishlistsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/signin'
    | '/signup'
    | '/applications'
    | '/assessments'
    | '/cv'
    | '/job-suggestions'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/wishlists'
    | '/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/signin'
    | '/signup'
    | '/applications'
    | '/assessments'
    | '/cv'
    | '/job-suggestions'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/wishlists'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_account'
    | '/about'
    | '/signin'
    | '/signup'
    | '/_account/applications'
    | '/_account/assessments'
    | '/_account/cv'
    | '/_account/job-suggestions'
    | '/_account/notifications'
    | '/_account/profile'
    | '/_account/settings'
    | '/_account/wishlists'
    | '/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AboutRoute: typeof AboutRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_account': {
      id: '/_account'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_account/wishlists': {
      id: '/_account/wishlists'
      path: '/wishlists'
      fullPath: '/wishlists'
      preLoaderRoute: typeof AccountWishlistsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_account/settings': {
      id: '/_account/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_account/profile': {
      id: '/_account/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_account/notifications': {
      id: '/_account/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_account/job-suggestions': {
      id: '/_account/job-suggestions'
      path: '/job-suggestions'
      fullPath: '/job-suggestions'
      preLoaderRoute: typeof AccountJobSuggestionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_account/cv': {
      id: '/_account/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof AccountCvRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_account/assessments': {
      id: '/_account/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AccountAssessmentsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_account/applications': {
      id: '/_account/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AccountApplicationsRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountApplicationsRoute: typeof AccountApplicationsRoute
  AccountAssessmentsRoute: typeof AccountAssessmentsRoute
  AccountCvRoute: typeof AccountCvRoute
  AccountJobSuggestionsRoute: typeof AccountJobSuggestionsRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountWishlistsRoute: typeof AccountWishlistsRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountApplicationsRoute: AccountApplicationsRoute,
  AccountAssessmentsRoute: AccountAssessmentsRoute,
  AccountCvRoute: AccountCvRoute,
  AccountJobSuggestionsRoute: AccountJobSuggestionsRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountWishlistsRoute: AccountWishlistsRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AboutRoute: AboutRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  JobsJobIdRoute: JobsJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
